### ISSUE TITLE
Does this still work in Magento 1.9.0.1?

### ISSUE THREAD

**Issue by shirtsofholl** [mobweb/MobWeb_SwitchCurrencyByURL#1]
Does this still work in Magento 1.9.0.1?

and can it create any conflicts with popular extensions?

many thanks!!!

**Comment by mobweb** [comment]
Yes, I've been using this extension in a project running the latest Magento version. Never had any problem with conflicts. Of course, if you do find that something is not working please let me know so I can fix it!
